import com.linecorp.centraldogma.client.CentralDogma;
import com.linecorp.centraldogma.client.Watcher;
import com.linecorp.centraldogma.common.Query;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws InterruptedException {
        CentralDogma cd = CentralDogma.forHost("127.0.0.1");
        Watcher<Object> watcher = cd.fileWatcher("test", "test", Query.ofJsonPath("/test.json"),
                                                 jsonNode -> {
                                                    return new Object();
                                                 });
        watcher.watch((rev, val) -> {
            System.out.println("new rev come");
        });

        while(true) {
            Thread.sleep(1000);
        }
    }
}
